package dev.firefly.simpletweaks.enchantments

import dev.firefly.simpletweaks.enchantments.generated.GeneratedEnchantments
import net.minecraft.enchantment.Enchantment
import net.minecraft.registry.RegistryKey
import net.minecraft.util.Formatting

/**
 * The single lookup point over **both** sources of enchantment metadata.
 *
 * 1.21's two generations of this project disagree about where an enchantment is defined:
 *
 * | source | what it holds | how it is maintained |
 * |---|---|---|
 * | [ModEnchantmentKeys] / [EnchantmentTiers] / [EnchantmentNameColors] | the original 56 | generated by `tools/gen-enchantments.ps1` from the 1.12.2 sources |
 * | [GeneratedEnchantments] | anything declared with `@ModEnchantment` | generated by KSP at build time |
 *
 * Rather than migrate 56 enchantments in one go (which would make every one of them a possible
 * regression), new enchantments are declared with the annotation and these functions merge the two.
 * A KSP-declared entry **wins** on a clash, so moving an enchantment over is just deleting it from
 * the legacy generator's table.
 *
 * [allKeys] is the union in that same order: legacy first, then KSP-declared. Nothing may depend on
 * that order beyond "stable" — the enchant index sorts by id itself.
 */
object EnchantmentMeta {

    /** Every known enchantment key, legacy + `@ModEnchantment`. */
    fun allKeys(): List<RegistryKey<Enchantment>> = ModEnchantmentKeys.ALL + GeneratedEnchantments.KEYS

    /** 1.12.2 `EnchantmentCategories` name, lowercased; `null` if unknown. */
    fun category(id: String): String? =
        GeneratedEnchantments.CATEGORY[id] ?: EnchantmentTiers.CATEGORY[id]

    /** 1.12.2 `ModEnchantmentType` name, lowercased; `null` if unknown. */
    fun type(id: String): String? =
        GeneratedEnchantments.TYPE[id] ?: EnchantmentTiers.TYPE[id]

    /** Max level; `null` if unknown. Callers that need a number use `?: 1`, as before. */
    fun maxLevel(id: String): Int? =
        GeneratedEnchantments.MAX_LEVEL[id] ?: EnchantmentTiers.MAX_LEVEL[id]

    /**
     * `Formatting` for the enchantment's displayed name, or `null` to leave the vanilla colour alone.
     *
     * **The fallback is load-bearing.** [EnchantmentNameColors] is a legacy generated table, so it
     * cannot know about a `@ModEnchantment` declaration. Reading that table directly is exactly why
     * `fast_bow` — declared `color = "blue"` — rendered in the default grey, i.e. indistinguishable
     * from a COMMON enchantment. Both the tooltip mixin and the enchant index go through here.
     *
     * The KSP side carries the colour as a plain `Formatting` **name** (a string) because the
     * processor must not depend on Minecraft classes; it is parsed back here.
     */
    @JvmStatic
    fun colorOf(id: String): Formatting? =
        GeneratedEnchantments.COLOR[id]?.let { Formatting.byName(it) } ?: EnchantmentNameColors.COLORS[id]
}
