package dev.firefly.simpletweaks.enchantments

import net.minecraft.util.Formatting

/**
 * Tooltip colour per enchantment, ported from 1.12.2 `EnchantmentCategories.color`.
 *
 * AUTO-GENERATED by tools/gen-enchantments.ps1 -- do not edit by hand.
 *
 * 1.12.2 expressed this through `ModEnchantments.decorateName` / `getTranslatedName`. Since 1.21
 * enchantments are data-driven and their displayed name comes from
 * `Enchantment.getName(RegistryEntry, int)`, the colour is applied there instead -- see
 * `mixin/EnchantmentNameColorMixin.java`.
 *
 * This is an explicit table rather than something derived from the JSON because the 1.12.2 tier
 * (`EnchantmentCategories`) has no 1.21 equivalent: 1.21 enchantments have no rarity, and the
 * `weight` field that the generator does write is ambiguous -- 1.12.2's `weight` is
 * `10 - rarity*2` clamped at 1, so MYTHIC and MYSTERY both come out as 1.
 */
object EnchantmentNameColors {

    /** Enchantment id (path only) -> 1.12.2 `EnchantmentCategories.color`. */
    val COLORS: Map<String, Formatting> = mapOf(
        "acid_attack" to Formatting.GRAY,
        "anti_knockback" to Formatting.GRAY,
        "aoe_attack" to Formatting.GREEN,
        "armor_breaker" to Formatting.GRAY,
        "assassin" to Formatting.BLUE,
        "auto_smelt" to Formatting.GRAY,
        "bloodlust" to Formatting.GREEN,
        "celestial_blessing" to Formatting.AQUA,
        "charged_strike" to Formatting.LIGHT_PURPLE,
        "combat_master" to Formatting.GRAY,
        "combo" to Formatting.GOLD,
        "crit" to Formatting.GOLD,
        "crit_damage" to Formatting.LIGHT_PURPLE,
        "damage_limiter" to Formatting.GOLD,
        "damage_reduction" to Formatting.LIGHT_PURPLE,
        "death_protection" to Formatting.DARK_RED,
        "delayed_recovery" to Formatting.LIGHT_PURPLE,
        "double_crit" to Formatting.GOLD,
        "double_strike" to Formatting.GOLD,
        "echo_shield" to Formatting.DARK_RED,
        "echo_shot" to Formatting.GOLD,
        "effect_bonus" to Formatting.GREEN,
        "execute" to Formatting.BLUE,
        "experience_stealer" to Formatting.BLUE,
        "extra_armor" to Formatting.BLUE,
        "fire_master" to Formatting.BLUE,
        "flight" to Formatting.GOLD,
        "gravity_strike" to Formatting.LIGHT_PURPLE,
        "grievous_wounds" to Formatting.DARK_RED,
        "healer" to Formatting.GREEN,
        "healing_blade" to Formatting.DARK_RED,
        "heavenly_punishment" to Formatting.AQUA,
        "hunters_mark" to Formatting.BLUE,
        "immortal" to Formatting.BLUE,
        "infinite_power" to Formatting.DARK_RED,
        "item_fixer" to Formatting.BLUE,
        "kill_aura" to Formatting.DARK_RED,
        "momentum" to Formatting.GREEN,
        "motion_bonus" to Formatting.GRAY,
        "multishot" to Formatting.BLUE,
        "piercing_arrow" to Formatting.BLUE,
        "prismatic_blessing" to Formatting.DARK_RED,
        "reforge" to Formatting.WHITE,
        "regeneration" to Formatting.GREEN,
        "resilience" to Formatting.GREEN,
        "saturation" to Formatting.GREEN,
        "soul_bound" to Formatting.GOLD,
        "starfall" to Formatting.DARK_RED,
        "super_knockback" to Formatting.GREEN,
        "swift_sneak" to Formatting.GREEN,
        "tracking_arrow" to Formatting.BLUE,
        "true_damage" to Formatting.LIGHT_PURPLE,
        "tunneling" to Formatting.LIGHT_PURPLE,
        "unbreakable" to Formatting.DARK_RED,
        "vitality" to Formatting.LIGHT_PURPLE,
        "void_protection" to Formatting.GRAY
    )

    fun of(id: String): Formatting? = COLORS[id]
}