package dev.firefly.simpletweaks.enchantments

import dev.firefly.simpletweaks.enchantments.generated.GeneratedEnchantments
import net.minecraft.enchantment.Enchantment
import net.minecraft.registry.RegistryKey

/**
 * The single lookup point over **both** sources of enchantment metadata.
 *
 * 1.21's two generations of this project disagree about where an enchantment is defined:
 *
 * | source | what it holds | how it is maintained |
 * |---|---|---|
 * | [ModEnchantmentKeys] / [EnchantmentTiers] | the original 55 | generated by `tools/gen-enchantments.ps1` from the 1.12.2 sources |
 * | [GeneratedEnchantments] | anything declared with `@ModEnchantment` | generated by KSP at build time |
 *
 * Rather than migrate 55 enchantments in one go (which would make every one of them a possible
 * regression), new enchantments are declared with the annotation and these functions merge the two.
 * A KSP-declared entry **wins** on a clash, so moving an enchantment over is just deleting it from
 * the legacy generator's table.
 *
 * [allKeys] is the union in that same order: legacy first, then KSP-declared. Nothing may depend on
 * that order beyond "stable" — the enchant index sorts by id itself.
 */
object EnchantmentMeta {

    /** Every known enchantment key, legacy + `@ModEnchantment`. */
    fun allKeys(): List<RegistryKey<Enchantment>> = ModEnchantmentKeys.ALL + GeneratedEnchantments.KEYS

    /** 1.12.2 `EnchantmentCategories` name, lowercased; `null` if unknown. */
    fun category(id: String): String? =
        GeneratedEnchantments.CATEGORY[id] ?: EnchantmentTiers.CATEGORY[id]

    /** 1.12.2 `ModEnchantmentType` name, lowercased; `null` if unknown. */
    fun type(id: String): String? =
        GeneratedEnchantments.TYPE[id] ?: EnchantmentTiers.TYPE[id]

    /** Max level; `null` if unknown. Callers that need a number use `?: 1`, as before. */
    fun maxLevel(id: String): Int? =
        GeneratedEnchantments.MAX_LEVEL[id] ?: EnchantmentTiers.MAX_LEVEL[id]

    /**
     * `Formatting` name for the enchantment's name colour, or `null` to leave it alone.
     *
     * Only KSP-declared enchantments have a colour here: the legacy entries carry theirs in the lang
     * file pipeline / `EnchantmentNameColors`, so this deliberately does **not** fall back.
     */
    fun color(id: String): String? = GeneratedEnchantments.COLOR[id]
}
