package dev.firefly.simpletweaks.enchantments

import dev.firefly.simpletweaks.enchantments.annotations.EnchantCategory
import dev.firefly.simpletweaks.enchantments.annotations.EnchantColor
import dev.firefly.simpletweaks.enchantments.generated.GeneratedEnchantments
import net.minecraft.enchantment.Enchantment
import net.minecraft.registry.RegistryKey
import net.minecraft.util.Formatting

/**
 * The single lookup point over **both** sources of enchantment metadata.
 *
 * 1.21's two generations of this project disagree about where an enchantment is defined:
 *
 * | source | what it holds | how it is maintained |
 * |---|---|---|
 * | [ModEnchantmentKeys] / [EnchantmentTiers] | the original 56 | generated by `tools/gen-enchantments.ps1` from the 1.12.2 sources |
 * | [GeneratedEnchantments] | anything declared with `@ModEnchantment` | generated by KSP at build time |
 *
 * Rather than migrate 56 enchantments in one go (which would make every one of them a possible
 * regression), new enchantments are declared with the annotation and these functions merge the two.
 * A KSP-declared entry **wins** on a clash, so moving an enchantment over is just deleting it from
 * the legacy generator's table.
 *
 * ## Why the two sides are bridged here instead of agreeing on one type
 * The KSP side is typed (`EnchantCategory` / `EnchantType` / `EnchantColor`) because the processor
 * reads annotation arguments and only ever sees enum *names*; the legacy tables are plain strings and
 * `Formatting` values because they are generated by `tools/gen-enchantments.ps1`, which parses the
 * 1.12.2 sources and knows nothing about this project's enums. Every caller — the tooltip mixin and
 * `client/EnchantInfoScreen` — wants the 1.12.2 names as lowercase strings, which is what
 * [EnchantCategory.toString] / [EnchantType.toString] already produce, so the enum-ness stops here.
 *
 * [allKeys] is the union in that same order: legacy first, then KSP-declared. Nothing may depend on
 * that order beyond "stable" — the enchant index sorts by id itself.
 */
object EnchantmentMeta {

    /**
     * The one 1.12.2 `decorateName` override that a colour table cannot express, because the name is
     * animated rather than coloured — see `InfinitePowerRainbow` and `EnchantmentNameColorMixin`.
     *
     * `infinite_power` is still generator-era, so it has no `@ModEnchantment` declaration to carry
     * `color = EnchantColor.RAINBOW`; this set keeps the behaviour alive in the meantime. When it is
     * migrated, delete the entry and declare the colour on the handler instead — [isRainbow] consults
     * both, so that is a one-line change with no other caller to touch.
     */
    private val LEGACY_RAINBOW = setOf("infinite_power")

    /** Every known enchantment key, legacy + `@ModEnchantment`. */
    fun allKeys(): List<RegistryKey<Enchantment>> = ModEnchantmentKeys.ALL + GeneratedEnchantments.KEYS

    /** 1.12.2 `EnchantmentCategories` name, lowercased; `null` if unknown. */
    fun category(id: String): String? =
        GeneratedEnchantments.CATEGORY[id]?.toString() ?: EnchantmentTiers.CATEGORY[id]

    /** 1.12.2 `ModEnchantmentType` name, lowercased; `null` if unknown. */
    fun type(id: String): String? =
        GeneratedEnchantments.TYPE[id]?.toString() ?: EnchantmentTiers.TYPE[id]

    /** Max level; `null` if unknown. Callers that need a number use `?: 1`, as before. */
    fun maxLevel(id: String): Int? =
        GeneratedEnchantments.MAX_LEVEL[id] ?: EnchantmentTiers.MAX_LEVEL[id]

    /**
     * The declared [EnchantColor], or `null` for a generator-era enchantment.
     *
     * `GeneratedEnchantments.COLOR` only holds *explicit* colours, so an annotation that leaves
     * `color` at its default ([EnchantColor.INHERIT]) is resolved here to its category's colour — the
     * same rule the old processor applied inline. Keeping the resolution on this side is what lets
     * `COLOR` stay a pure "was it overridden?" table.
     */
    fun color(id: String): EnchantColor? =
        GeneratedEnchantments.COLOR[id] ?: GeneratedEnchantments.CATEGORY[id]?.color

    /**
     * `true` when the displayed name must be rendered as a per-character rainbow instead of a flat
     * colour. Checked by `EnchantmentNameColorMixin` **before** [colorOf], because
     * [EnchantColor.RAINBOW] carries no `Formatting` and would otherwise fall through.
     *
     * `@JvmStatic` because the caller is the Java mixin — a Kotlin `object` member is not static from
     * Java's point of view, and without this the call does not compile ("cannot reference a non-static
     * method from a static context").
     */
    @JvmStatic
    fun isRainbow(id: String): Boolean =
        GeneratedEnchantments.COLOR[id] == EnchantColor.RAINBOW || id in LEGACY_RAINBOW

    /**
     * Colour per 1.12.2 tier, **derived from [EnchantCategory]** instead of stored in its own table.
     *
     * This replaces the generated `EnchantmentNameColors` table. Before that table was deleted, all 54
     * of its entries were checked against this derivation and agreed **54/54** — which is expected,
     * because 1.12.2's `EnchantmentCategories(rarity, color)` makes the colour a *property of the
     * category*. A second copy of that mapping could only ever drift from the first.
     */
    private val TIER_COLORS: Map<String, Formatting> =
        EnchantCategory.entries
            .mapNotNull { cat -> cat.color.formatting?.let { cat.toString() to it } }
            .toMap()

    /**
     * `Formatting` for the enchantment's displayed name, or `null` to leave the vanilla colour alone.
     *
     * Two sources, in order:
     *  1. a `@ModEnchantment` declaration — its explicit [EnchantColor], else its category's colour,
     *     which is what [color] resolves;
     *  2. a generator-era enchantment, whose colour comes from its 1.12.2 tier via [TIER_COLORS].
     *
     * **Source 1 is why this indirection exists at all.** The old code consulted the generated colour
     * table first, which by construction knew nothing about `@ModEnchantment` — so `fast_bow`, declared
     * `color = EnchantColor.BLUE`, rendered in the default grey, i.e. indistinguishable from a COMMON
     * enchantment. Both the tooltip mixin and the enchant index go through here.
     */
    @JvmStatic
    fun colorOf(id: String): Formatting? =
        color(id)?.formatting ?: EnchantmentTiers.CATEGORY[id]?.let { TIER_COLORS[it] }
}
