package dev.firefly.simpletweaks.enchantments

import dev.firefly.simpletweaks.SimpleTweaks
import net.minecraft.enchantment.Enchantment
import net.minecraft.registry.RegistryKey
import net.minecraft.registry.RegistryKeys
import net.minecraft.util.Identifier

/**
 * RegistryKeys for all 54 enchantments.
 *
 * Since 1.21 the enchantment *definitions* live in the data/simple_tweaks/enchantment/ folder
 * (one JSON per enchantment), so code only ever holds a [RegistryKey]. This replaces the 1.12.2
 * object EnchantX : ModEnchantments(...) classes, which no longer exist.
 *
 * To read a level:
 * `
 * getItemSpecificEnchantLevel(stack, ModEnchantmentKeys.ACID_ATTACK)
 * `
 * (see util/EnchantmentsUtil.kt -- it matches by key inside the stack's own enchantment component,
 * so no registry lookup or world access is needed).
 *
 * AUTO-GENERATED by tools/gen-enchantments.ps1 -- do not edit by hand.
 */
object ModEnchantmentKeys {

    private fun of(id: String): RegistryKey<Enchantment> =
        RegistryKey.of(RegistryKeys.ENCHANTMENT, Identifier.of(SimpleTweaks.MOD_ID, id))

    val ACID_ATTACK: RegistryKey<Enchantment> = of("acid_attack")
    val ANTI_KNOCKBACK: RegistryKey<Enchantment> = of("anti_knockback")
    val AOE_ATTACK: RegistryKey<Enchantment> = of("aoe_attack")
    val ARMOR_BREAKER: RegistryKey<Enchantment> = of("armor_breaker")
    val ASSASSIN: RegistryKey<Enchantment> = of("assassin")
    val AUTO_SMELT: RegistryKey<Enchantment> = of("auto_smelt")
    val BLOODLUST: RegistryKey<Enchantment> = of("bloodlust")
    val CELESTIAL_BLESSING: RegistryKey<Enchantment> = of("celestial_blessing")
    val CHARGED_STRIKE: RegistryKey<Enchantment> = of("charged_strike")
    val COMBAT_MASTER: RegistryKey<Enchantment> = of("combat_master")
    val COMBO: RegistryKey<Enchantment> = of("combo")
    val CRIT_DAMAGE: RegistryKey<Enchantment> = of("crit_damage")
    val DAMAGE_LIMITER: RegistryKey<Enchantment> = of("damage_limiter")
    val DAMAGE_REDUCTION: RegistryKey<Enchantment> = of("damage_reduction")
    val DEATH_PROTECTION: RegistryKey<Enchantment> = of("death_protection")
    val DELAYED_RECOVERY: RegistryKey<Enchantment> = of("delayed_recovery")
    val DOUBLE_CRIT: RegistryKey<Enchantment> = of("double_crit")
    val DOUBLE_STRIKE: RegistryKey<Enchantment> = of("double_strike")
    val ECHO_SHIELD: RegistryKey<Enchantment> = of("echo_shield")
    val ECHO_SHOT: RegistryKey<Enchantment> = of("echo_shot")
    val EFFECT_BONUS: RegistryKey<Enchantment> = of("effect_bonus")
    val EXECUTE: RegistryKey<Enchantment> = of("execute")
    val EXPERIENCE_STEALER: RegistryKey<Enchantment> = of("experience_stealer")
    val EXTRA_ARMOR: RegistryKey<Enchantment> = of("extra_armor")
    val FIRE_MASTER: RegistryKey<Enchantment> = of("fire_master")
    val FLIGHT: RegistryKey<Enchantment> = of("flight")
    val GRAVITY_STRIKE: RegistryKey<Enchantment> = of("gravity_strike")
    val GRIEVOUS_WOUNDS: RegistryKey<Enchantment> = of("grievous_wounds")
    val HEALER: RegistryKey<Enchantment> = of("healer")
    val HEALING_BLADE: RegistryKey<Enchantment> = of("healing_blade")
    val HEAVENLY_PUNISHMENT: RegistryKey<Enchantment> = of("heavenly_punishment")
    val HUNTERS_MARK: RegistryKey<Enchantment> = of("hunters_mark")
    val IMMORTAL: RegistryKey<Enchantment> = of("immortal")
    val INFINITE_POWER: RegistryKey<Enchantment> = of("infinite_power")
    val ITEM_FIXER: RegistryKey<Enchantment> = of("item_fixer")
    val KILL_AURA: RegistryKey<Enchantment> = of("kill_aura")
    val MOMENTUM: RegistryKey<Enchantment> = of("momentum")
    val MOTION_BONUS: RegistryKey<Enchantment> = of("motion_bonus")
    val MULTISHOT: RegistryKey<Enchantment> = of("multishot")
    val PRISMATIC_BLESSING: RegistryKey<Enchantment> = of("prismatic_blessing")
    val REFORGE: RegistryKey<Enchantment> = of("reforge")
    val REGENERATION: RegistryKey<Enchantment> = of("regeneration")
    val RESILIENCE: RegistryKey<Enchantment> = of("resilience")
    val SATURATION: RegistryKey<Enchantment> = of("saturation")
    val SOUL_BOUND: RegistryKey<Enchantment> = of("soul_bound")
    val STARFALL: RegistryKey<Enchantment> = of("starfall")
    val SUPER_KNOCKBACK: RegistryKey<Enchantment> = of("super_knockback")
    val SWIFT_SNEAK: RegistryKey<Enchantment> = of("swift_sneak")
    val TRACKING_ARROW: RegistryKey<Enchantment> = of("tracking_arrow")
    val TRUE_DAMAGE: RegistryKey<Enchantment> = of("true_damage")
    val TUNNELING: RegistryKey<Enchantment> = of("tunneling")
    val UNBREAKABLE: RegistryKey<Enchantment> = of("unbreakable")
    val VITALITY: RegistryKey<Enchantment> = of("vitality")
    val VOID_PROTECTION: RegistryKey<Enchantment> = of("void_protection")



    /** All  keys, for diagnostics/iteration. */
    val ALL: List<RegistryKey<Enchantment>> = listOf(ACID_ATTACK, ANTI_KNOCKBACK, AOE_ATTACK, ARMOR_BREAKER, ASSASSIN, AUTO_SMELT, BLOODLUST, CELESTIAL_BLESSING, CHARGED_STRIKE, COMBAT_MASTER, COMBO, CRIT_DAMAGE, DAMAGE_LIMITER, DAMAGE_REDUCTION, DEATH_PROTECTION, DELAYED_RECOVERY, DOUBLE_CRIT, DOUBLE_STRIKE, ECHO_SHIELD, ECHO_SHOT, EFFECT_BONUS, EXECUTE, EXPERIENCE_STEALER, EXTRA_ARMOR, FIRE_MASTER, FLIGHT, GRAVITY_STRIKE, GRIEVOUS_WOUNDS, HEALER, HEALING_BLADE, HEAVENLY_PUNISHMENT, HUNTERS_MARK, IMMORTAL, INFINITE_POWER, ITEM_FIXER, KILL_AURA, MOMENTUM, MOTION_BONUS, MULTISHOT, PRISMATIC_BLESSING, REFORGE, REGENERATION, RESILIENCE, SATURATION, SOUL_BOUND, STARFALL, SUPER_KNOCKBACK, SWIFT_SNEAK, TRACKING_ARROW, TRUE_DAMAGE, TUNNELING, UNBREAKABLE, VITALITY, VOID_PROTECTION)
}